---
name: Is Fork

# owner: @camunda/engineering-operations

description: |
  Checks if the current job runs on code from a forked repository.
  This information can be used to disable certain CI features that are not
  available on forks (e.g. access to secrets).

inputs: {}

outputs:
  is-fork:
    description: Output whether the current job runs on code from a forked repository
    value: ${{ steps.detect-fork.outputs.is-fork == 'true' }}

runs:
  using: composite
  steps:
  - id: detect-fork
    env:
      GH_EVENT_PR_FORK: ${{ github.event.pull_request.head.repo.fork }}
      GH_REPOSITORY: ${{ github.repository }}
    shell: bash
    run: |
      if [[ "$GH_EVENT_PR_FORK" == "true" || "$GH_REPOSITORY" != "camunda/camunda" ]]; then
        echo is-fork=true | tee -a "$GITHUB_OUTPUT"
      else
        echo is-fork=false | tee -a "$GITHUB_OUTPUT"
      fi
